import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Switch } from "@/components/ui/switch";
import {
  Sparkles, FileText, PenTool, Trash2, ChevronDown, ChevronUp,
  Loader2, Globe, Eye, EyeOff, Bot, ExternalLink, Clock
} from "lucide-react";
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";
import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import type { SeoArticle } from "@shared/schema";
import DashboardLayout from "@/components/dashboard-layout";

const KEYWORD_PRESETS = [
  { label: "求荷求車", value: "求荷求車, マッチング, 運送, 物流" },
  { label: "空車情報", value: "空車, 空車情報, 配車, 運送会社" },
  { label: "物流DX", value: "物流DX, デジタル化, テクノロジー, 効率化" },
  { label: "コスト削減", value: "コスト削減, 物流費, 運賃, 効率化" },
  { label: "2024年問題", value: "2024年問題, ドライバー不足, 働き方改革" },
  { label: "配車計画", value: "配車, AI, 自動化, 効率化" },
  { label: "共同配送", value: "共同配送, 混載, コスト削減, 物流効率" },
  { label: "帰り便", value: "帰り便, 空車, コスト削減, 求荷求車" },
];

export default function AdminSeo() {
  const { toast } = useToast();
  const [topic, setTopic] = useState("");
  const [keywords, setKeywords] = useState("");
  const [notes, setNotes] = useState("");
  const [autoPublish, setAutoPublish] = useState(true);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const { data: articles, isLoading } = useQuery<SeoArticle[]>({
    queryKey: ["/api/admin/seo-articles"],
  });

  const generateMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/admin/seo-articles/generate", { topic, keywords, notes, autoPublish });
      return res.json();
    },
    onSuccess: () => {
      toast({ title: "記事を生成しました" });
      setTopic("");
      setKeywords("");
      setNotes("");
      queryClient.invalidateQueries({ queryKey: ["/api/admin/seo-articles"] });
    },
    onError: () => {
      toast({ title: "記事の生成に失敗しました", variant: "destructive" });
    },
  });

  const togglePublishMutation = useMutation({
    mutationFn: async ({ id, status }: { id: string; status: string }) => {
      const newStatus = status === "published" ? "draft" : "published";
      await apiRequest("PATCH", `/api/admin/seo-articles/${id}`, { status: newStatus });
    },
    onSuccess: () => {
      toast({ title: "ステータスを更新しました" });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/seo-articles"] });
    },
    onError: () => {
      toast({ title: "更新に失敗しました", variant: "destructive" });
    },
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      await apiRequest("DELETE", `/api/admin/seo-articles/${id}`);
    },
    onSuccess: () => {
      toast({ title: "記事を削除しました" });
      queryClient.invalidateQueries({ queryKey: ["/api/admin/seo-articles"] });
    },
    onError: () => {
      toast({ title: "記事の削除に失敗しました", variant: "destructive" });
    },
  });

  const publishedCount = articles?.filter(a => a.status === "published").length || 0;
  const autoCount = articles?.filter(a => a.autoGenerated).length || 0;

  return (
    <DashboardLayout>
      <div className="px-4 sm:px-6 py-6 overflow-y-auto" style={{ maxHeight: "calc(100vh - 64px)" }}>
        <div className="mb-6">
          <h1 className="text-xl font-bold text-foreground" data-testid="text-page-title">SEOコラム記事管理</h1>
          <p className="text-sm text-muted-foreground mt-1">AIによるコラム記事の自動生成・管理</p>
        </div>

        <div className="max-w-4xl space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <Card>
              <CardContent className="p-4 flex items-center gap-3">
                <FileText className="w-8 h-8 text-primary shrink-0" />
                <div>
                  <p className="text-2xl font-bold text-foreground" data-testid="text-total-count">{articles?.length || 0}</p>
                  <p className="text-xs text-muted-foreground">総記事数</p>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-4 flex items-center gap-3">
                <Globe className="w-8 h-8 text-green-600 shrink-0" />
                <div>
                  <p className="text-2xl font-bold text-foreground" data-testid="text-published-count">{publishedCount}</p>
                  <p className="text-xs text-muted-foreground">公開中</p>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-4 flex items-center gap-3">
                <Bot className="w-8 h-8 text-blue-600 shrink-0" />
                <div>
                  <p className="text-2xl font-bold text-foreground" data-testid="text-auto-count">{autoCount}</p>
                  <p className="text-xs text-muted-foreground">自動生成</p>
                </div>
              </CardContent>
            </Card>
          </div>

          <Card>
            <CardContent className="p-4">
              <h2 className="text-base font-bold text-foreground mb-2 flex items-center gap-2">
                <Bot className="w-4 h-4 text-primary" />
                自動生成について
              </h2>
              <p className="text-sm text-muted-foreground">
                毎日朝6時に物流・運送業界に関するSEOコラム記事が自動的に生成・公開されます。
                30種類のテーマ（求荷求車、空車活用、物流DXなど）からランダムに選択され、サーバー起動時にも当日分がなければ自動生成されます。
              </p>
              <div className="flex items-center gap-2 mt-3">
                <Clock className="w-3.5 h-3.5 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">次回生成: 毎日 6:00 AM (サーバー起動時)</span>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <h2 className="text-base font-bold text-foreground mb-4 flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary" />
                手動で記事を生成
              </h2>
              <div className="space-y-4">
                <div>
                  <Label htmlFor="seo-topic">記事テーマ</Label>
                  <Input
                    id="seo-topic"
                    placeholder="例: 求荷求車サービスのメリット"
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    className="mt-1"
                    data-testid="input-seo-topic"
                  />
                </div>
                <div>
                  <Label className="mb-2 block">キーワードプリセット</Label>
                  <div className="flex flex-wrap gap-2">
                    {KEYWORD_PRESETS.map((preset) => (
                      <Badge
                        key={preset.label}
                        variant={keywords === preset.value ? "default" : "secondary"}
                        className="cursor-pointer"
                        onClick={() => {
                          setKeywords(keywords === preset.value ? "" : preset.value);
                          if (!topic) setTopic(preset.label + "に関する最新動向");
                        }}
                        data-testid={`badge-preset-${preset.label}`}
                      >
                        {preset.label}
                      </Badge>
                    ))}
                  </div>
                </div>
                <div>
                  <Label htmlFor="seo-keywords">キーワード（カンマ区切り）</Label>
                  <Input
                    id="seo-keywords"
                    placeholder="例: 求荷求車, マッチング, 運送"
                    value={keywords}
                    onChange={(e) => setKeywords(e.target.value)}
                    className="mt-1"
                    data-testid="input-seo-keywords"
                  />
                </div>
                <div>
                  <Label htmlFor="seo-notes">備考・指示</Label>
                  <Textarea
                    id="seo-notes"
                    placeholder="記事の方向性や含めたい情報など..."
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    className="mt-1 min-h-[80px]"
                    data-testid="input-seo-notes"
                  />
                </div>
                <div className="flex items-center gap-3">
                  <Switch
                    id="auto-publish"
                    checked={autoPublish}
                    onCheckedChange={setAutoPublish}
                    data-testid="switch-auto-publish"
                  />
                  <Label htmlFor="auto-publish" className="text-sm">生成後すぐに公開する</Label>
                </div>
                <Button
                  className="w-full"
                  onClick={() => generateMutation.mutate()}
                  disabled={!topic.trim() || generateMutation.isPending}
                  data-testid="button-generate-article"
                >
                  {generateMutation.isPending ? (
                    <Loader2 className="w-4 h-4 mr-1.5 animate-spin" />
                  ) : (
                    <Sparkles className="w-4 h-4 mr-1.5" />
                  )}
                  {generateMutation.isPending ? "生成中..." : "AIで記事を生成"}
                </Button>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <div className="flex items-center justify-between gap-2 mb-4 flex-wrap">
                <h2 className="text-base font-bold text-foreground flex items-center gap-2">
                  <FileText className="w-4 h-4 text-primary" />
                  記事一覧
                </h2>
                <a href="/columns" target="_blank" rel="noopener noreferrer">
                  <Button variant="outline" size="sm" data-testid="button-view-public">
                    <ExternalLink className="w-3.5 h-3.5 mr-1" />
                    公開ページ
                  </Button>
                </a>
              </div>
              {isLoading ? (
                <div className="space-y-3">
                  {Array.from({ length: 2 }).map((_, i) => (
                    <Skeleton key={i} className="h-16 w-full" />
                  ))}
                </div>
              ) : !articles || articles.length === 0 ? (
                <div className="text-center py-6">
                  <PenTool className="w-10 h-10 text-muted-foreground/20 mx-auto mb-2" />
                  <p className="text-sm text-muted-foreground" data-testid="text-empty-state">記事はまだありません</p>
                  <p className="text-xs text-muted-foreground mt-1">手動で生成するか、自動生成をお待ちください</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {articles.map((article) => (
                    <div key={article.id} className="border rounded-md" data-testid={`card-article-${article.id}`}>
                      <div
                        className="flex items-center justify-between gap-2 flex-wrap p-3 cursor-pointer"
                        onClick={() => setExpandedId(expandedId === article.id ? null : article.id)}
                        data-testid={`button-expand-article-${article.id}`}
                      >
                        <div className="min-w-0 flex-1">
                          <p className="text-sm font-medium text-foreground truncate">{article.title}</p>
                          <div className="flex items-center gap-2 flex-wrap mt-1">
                            <Badge variant={article.status === "published" ? "default" : "secondary"} className="text-xs">
                              {article.status === "published" ? "公開" : "下書き"}
                            </Badge>
                            {article.autoGenerated && (
                              <Badge variant="outline" className="text-xs">
                                <Bot className="w-3 h-3 mr-0.5" />
                                自動
                              </Badge>
                            )}
                            {article.keywords && article.keywords.split(",").slice(0, 2).map((kw, i) => (
                              <Badge key={i} variant="secondary" className="text-xs">{kw.trim()}</Badge>
                            ))}
                            <span className="text-xs text-muted-foreground">
                              {new Date(article.createdAt).toLocaleDateString("ja-JP")}
                            </span>
                          </div>
                        </div>
                        <div className="flex items-center gap-1 shrink-0">
                          <Button
                            size="icon"
                            variant="ghost"
                            onClick={(e) => {
                              e.stopPropagation();
                              togglePublishMutation.mutate({ id: article.id, status: article.status });
                            }}
                            data-testid={`button-toggle-publish-${article.id}`}
                          >
                            {article.status === "published" ? (
                              <EyeOff className="w-4 h-4 text-muted-foreground" />
                            ) : (
                              <Eye className="w-4 h-4 text-green-600" />
                            )}
                          </Button>
                          <Button
                            size="icon"
                            variant="ghost"
                            onClick={(e) => {
                              e.stopPropagation();
                              deleteMutation.mutate(article.id);
                            }}
                            data-testid={`button-delete-article-${article.id}`}
                          >
                            <Trash2 className="w-4 h-4 text-destructive" />
                          </Button>
                          {expandedId === article.id ? (
                            <ChevronUp className="w-4 h-4 text-muted-foreground" />
                          ) : (
                            <ChevronDown className="w-4 h-4 text-muted-foreground" />
                          )}
                        </div>
                      </div>
                      {expandedId === article.id && (
                        <div className="border-t p-3">
                          {article.metaDescription && (
                            <div className="mb-3 p-2 bg-muted/50 rounded-md">
                              <p className="text-xs text-muted-foreground font-medium mb-1">メタディスクリプション:</p>
                              <p className="text-xs text-foreground">{article.metaDescription}</p>
                            </div>
                          )}
                          {article.slug && (
                            <div className="mb-3">
                              <p className="text-xs text-muted-foreground">
                                URL: <a href={`/columns/${article.slug}`} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">/columns/{article.slug}</a>
                              </p>
                            </div>
                          )}
                          <div
                            className="prose prose-sm dark:prose-invert max-w-none text-foreground"
                            dangerouslySetInnerHTML={{ __html: renderMarkdown(article.content) }}
                            data-testid={`text-article-content-${article.id}`}
                          />
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </DashboardLayout>
  );
}

function renderMarkdown(md: string): string {
  return md
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/^### (.+)$/gm, '<h3 class="text-base font-bold mt-4 mb-2">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 class="text-lg font-bold mt-5 mb-2">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 class="text-xl font-bold mt-6 mb-3">$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^- (.+)$/gm, '<li class="ml-4">$1</li>')
    .replace(/\n\n/g, "</p><p class='mt-2'>")
    .replace(/\n/g, "<br/>")
    .replace(/^/, "<p>")
    .replace(/$/, "</p>");
}
