import { db } from "./db";
import { cargoListings, truckListings, users } from "@shared/schema";
import { sql } from "drizzle-orm";
import bcrypt from "bcrypt";

export async function seedDatabase() {
  const existingUsers = await db.select({ count: sql<number>`count(*)` }).from(users);
  if (Number(existingUsers[0].count) === 0) {
    const adminPassword = await bcrypt.hash("admin123", 10);
    await db.insert(users).values({
      username: "admin",
      password: adminPassword,
      companyName: "トラマッチ運営",
      phone: "03-0000-0000",
      email: "admin@tramatch.jp",
      userType: "admin",
      role: "admin",
      approved: true,
    });
    console.log("Admin user created (username: admin, password: admin123)");
  }

  const existingCargo = await db.select({ count: sql<number>`count(*)` }).from(cargoListings);
  const existingTrucks = await db.select({ count: sql<number>`count(*)` }).from(truckListings);

  if (Number(existingCargo[0].count) > 0 || Number(existingTrucks[0].count) > 0) {
    console.log("Database already has data, skipping seed.");
    return;
  }

  await db.insert(cargoListings).values([
    {
      transportType: "スポット",
      title: "東京→大阪 食品冷蔵便",
      departureArea: "東京",
      departureAddress: "江東区有明",
      departureTime: "08:00",
      arrivalArea: "大阪",
      arrivalAddress: "大阪市住之江区南港",
      arrivalTime: "午前中",
      cargoType: "食品（冷蔵）",
      weight: "8t",
      desiredDate: "2026/03/05",
      arrivalDate: "2026/03/06",
      vehicleType: "10t車",
      bodyType: "冷蔵車",
      temperatureControl: "冷蔵（0〜10℃）",
      price: "120,000",
      highwayFee: "込み",
      consolidation: "不可",
      driverWork: "フォークリフト",
      packageCount: "20パレット",
      loadingMethod: "パレット積み",
      description: "冷蔵食品の輸送です。温度管理が必要です。集荷は朝8時希望。",
      companyName: "東京フーズ株式会社",
      contactPhone: "03-1234-5678",
      contactEmail: "logistics@tokyofoods.co.jp",
    },
    {
      transportType: "定期",
      title: "名古屋→福岡 機械部品",
      departureArea: "愛知",
      departureAddress: "名古屋市港区",
      departureTime: "午前中",
      arrivalArea: "福岡",
      arrivalAddress: "福岡市東区",
      arrivalTime: "指定なし",
      cargoType: "機械部品",
      weight: "5t",
      desiredDate: "2026/03/08",
      arrivalDate: "2026/03/09",
      vehicleType: "10t車",
      bodyType: "ウイング",
      temperatureControl: "常温",
      price: "95,000",
      highwayFee: "別途",
      consolidation: "可",
      driverWork: "フォークリフト",
      packageCount: "15箱",
      loadingMethod: "段ボール",
      description: "精密機械部品のため丁寧な扱いをお願いします。梱包済み。",
      companyName: "中部メカニクス株式会社",
      contactPhone: "052-987-6543",
      contactEmail: "shipping@chubu-mech.co.jp",
    },
    {
      transportType: "スポット",
      title: "大阪→東京 アパレル商品",
      departureArea: "大阪",
      departureAddress: "大阪市中央区",
      departureTime: "午後",
      arrivalArea: "東京",
      arrivalAddress: "渋谷区神宮前",
      arrivalTime: "午前中",
      cargoType: "アパレル",
      weight: "3t",
      desiredDate: "2026/03/10",
      arrivalDate: "2026/03/11",
      vehicleType: "4t車",
      bodyType: "バン",
      temperatureControl: "指定なし",
      price: "65,000",
      highwayFee: "込み",
      consolidation: "不可",
      driverWork: "手積み手降ろし",
      packageCount: "50箱",
      loadingMethod: "段ボール",
      description: "春物アパレル商品。ハンガーラック使用。雨濡れ厳禁。",
      companyName: "関西アパレル株式会社",
      contactPhone: "06-5555-1234",
      contactEmail: "info@kansai-apparel.co.jp",
    },
    {
      transportType: "チャーター",
      title: "北海道→東京 農産物",
      departureArea: "北海道",
      departureAddress: "帯広市西",
      departureTime: "06:00",
      arrivalArea: "東京",
      arrivalAddress: "大田区東海",
      arrivalTime: "午前中",
      cargoType: "農産物",
      weight: "10t",
      desiredDate: "2026/03/12",
      arrivalDate: "2026/03/14",
      vehicleType: "大型車",
      bodyType: "ウイング",
      temperatureControl: "常温",
      price: "180,000",
      highwayFee: "込み",
      consolidation: "不可",
      driverWork: "作業なし（車上渡し）",
      packageCount: "バラ",
      loadingMethod: "バラ積み",
      description: "じゃがいも・玉ねぎの大量輸送。鮮度管理のため迅速な配送をお願いします。",
      companyName: "北海道農産直送株式会社",
      contactPhone: "011-222-3333",
      contactEmail: "nouhan@hokkaido-farm.co.jp",
    },
    {
      transportType: "スポット",
      title: "埼玉→仙台 建材",
      departureArea: "埼玉",
      departureAddress: "川口市",
      departureTime: "07:00",
      arrivalArea: "宮城",
      arrivalAddress: "仙台市宮城野区",
      arrivalTime: "午後",
      cargoType: "建材",
      weight: "7t",
      desiredDate: "2026/03/15",
      arrivalDate: "2026/03/16",
      vehicleType: "10t車",
      bodyType: "平ボディ",
      temperatureControl: "指定なし",
      price: "",
      highwayFee: "別途",
      consolidation: "不可",
      driverWork: "クレーン",
      packageCount: "",
      loadingMethod: "その他",
      description: "木材・合板の輸送。長尺物あり（最大4m）。荷台シート掛け必要。",
      companyName: "関東建材株式会社",
      contactPhone: "048-777-8888",
      contactEmail: "haiso@kanto-kenzai.co.jp",
    },
    {
      transportType: "スポット",
      title: "神奈川→千葉 フレコン鋼材",
      departureArea: "神奈川",
      departureAddress: "横浜市鶴見区",
      departureTime: "09:00",
      arrivalArea: "千葉",
      arrivalAddress: "千葉市中央区",
      arrivalTime: "指定なし",
      cargoType: "鋼材",
      weight: "15t",
      desiredDate: "2026/03/17",
      arrivalDate: "2026/03/17",
      vehicleType: "大型車",
      bodyType: "平ボディ",
      temperatureControl: "指定なし",
      price: "40,000",
      highwayFee: "込み",
      consolidation: "不可",
      driverWork: "クレーン",
      packageCount: "",
      loadingMethod: "フレコン",
      description: "連絡は携帯電話へお願いします。",
      companyName: "津田運送株式会社",
      contactPhone: "080-7121-xxxx",
      contactEmail: "",
    },
    {
      transportType: "チャーター",
      title: "神奈川→香川 シャフト",
      departureArea: "神奈川",
      departureAddress: "横浜市",
      departureTime: "指定なし",
      arrivalArea: "香川",
      arrivalAddress: "香川郡直島町",
      arrivalTime: "指定なし",
      cargoType: "シャフト",
      weight: "13t",
      desiredDate: "2026/03/19",
      arrivalDate: "",
      vehicleType: "大型車",
      bodyType: "平ボディ",
      temperatureControl: "指定なし",
      price: "150,000",
      highwayFee: "高速代なし",
      consolidation: "可",
      driverWork: "未入力",
      packageCount: "",
      loadingMethod: "バラ積み",
      description: "連絡は携帯電話へお願いします。080-7121-xxxx",
      companyName: "ビックネット株式会社",
      contactPhone: "045-xxx-xxxx",
      contactEmail: "",
    },
    {
      transportType: "スポット",
      title: "川崎→浦安 フレコン",
      departureArea: "神奈川",
      departureAddress: "川崎市川崎区",
      departureTime: "指定なし",
      arrivalArea: "千葉",
      arrivalAddress: "浦安市",
      arrivalTime: "指定なし",
      cargoType: "フレコン",
      weight: "13t",
      desiredDate: "2026/03/17",
      arrivalDate: "",
      vehicleType: "大型車",
      bodyType: "平ボディ",
      temperatureControl: "指定なし",
      price: "22,000",
      highwayFee: "高速代なし",
      consolidation: "不可",
      driverWork: "未入力",
      packageCount: "",
      loadingMethod: "フレコン",
      description: "",
      companyName: "株式会社エー・アイ・コーポレーション",
      contactPhone: "044-xxx-xxxx",
      contactEmail: "",
    },
  ]);

  await db.insert(truckListings).values([
    {
      title: "10t車 関東→関西 空車あり",
      currentArea: "東京",
      destinationArea: "大阪",
      vehicleType: "10t車",
      maxWeight: "10t",
      availableDate: "2026/03/06",
      price: "100,000",
      description: "ウイング車。パレット対応可能。翌日着可。高速道路利用。",
      companyName: "首都圏運送株式会社",
      contactPhone: "03-9876-5432",
      contactEmail: "dispatch@shutoken-unsou.co.jp",
    },
    {
      title: "4t車 大阪→名古屋 空車",
      currentArea: "大阪",
      destinationArea: "愛知",
      vehicleType: "4t車",
      maxWeight: "4t",
      availableDate: "2026/03/07",
      price: "45,000",
      description: "箱車。冷蔵機能なし。午前中出発可能。ドライバー1名。",
      companyName: "大阪ロジスティクス株式会社",
      contactPhone: "06-1111-2222",
      contactEmail: "info@osaka-logistics.co.jp",
    },
    {
      title: "大型トレーラー 九州→関東",
      currentArea: "福岡",
      destinationArea: "東京",
      vehicleType: "トレーラー",
      maxWeight: "20t",
      availableDate: "2026/03/09",
      price: "200,000",
      description: "海上コンテナ輸送対応。20ftコンテナ可能。福岡港付近から出発。",
      companyName: "九州物流株式会社",
      contactPhone: "092-333-4444",
      contactEmail: "haisha@kyushu-butsuryu.co.jp",
    },
    {
      title: "2t車 東京都内 空車",
      currentArea: "東京",
      destinationArea: "東京",
      vehicleType: "2t車",
      maxWeight: "2t",
      availableDate: "2026/03/05",
      price: "25,000",
      description: "都内配送専門。狭い道路も対応可能。引越し・小口配送に最適。ゲート車。",
      companyName: "東京デリバリー株式会社",
      contactPhone: "03-5555-6666",
      contactEmail: "delivery@tokyo-delivery.co.jp",
    },
    {
      title: "冷蔵10t車 東北→関東",
      currentArea: "宮城",
      destinationArea: "埼玉",
      vehicleType: "10t車",
      maxWeight: "10t",
      availableDate: "2026/03/11",
      price: "130,000",
      description: "冷蔵冷凍車。-20度まで対応。食品輸送実績多数。HACCP対応ドライバー。",
      companyName: "東北冷蔵運輸株式会社",
      contactPhone: "022-888-9999",
      contactEmail: "reizo@tohoku-reizo.co.jp",
    },
  ]);

  console.log("Seed data inserted successfully.");
}
